require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

  Exclude:
    - Rakefile
    - .gitignore
    - .rspec
    - .rubocop.yml

    - Gemfile.lock
    - "*.gemspec"
    - CHANGELOG.md
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*
    - spec/**/*
